### ISSUE TITLE
Question: Any spin-offs / reconsideration to work on master only ( no develop branch )

### ISSUE THREAD

**Issue by EugenMayer** [datasift/gitflow#109]
in our teams, we less and less instrumentalize the develop branch but rather stick to master only.

The reason for that is formally, since there is no need for the master branch in gitflow - it is a pure synthetic branch which nobody does any work on or uses it. 

- you never check it out to trace anything. You either are on `develop` or you checkout a specific `tag` you want to verify something against. But checking out master is somewhat "the latest stable release" - which can be simply derived from the (hopefully semver) tags anytime
- you do never commit or do anything to the branch. All operations are automations 

It is a release branch which includes all tags - and that is about all it is. Considering that tags are not limited to a branch or whatsoever, you can easily have the entire gitlfow branch-ecosystem without using the develop branch, treating the master branch as "develop" and just removing the extra merge "to master" when you release. A release  is one tag on a commit and if needed, also a `release/<version>` branch for long term support.

I wonder if there is any discussion about this or if there are any tool-spinoffs for that or if i could even use hubflow to be configured to act like that?

Thanks for any hints!

**Comment by stuartherbert** [comment]
Hi Eugen,

I think there's two questions here: the purpose of the master branch in Gitflow, and support for the alternative branching model that you're describing.

The `master` branch in Gitflow serves an important purpose: it's the only branch that contains only released code. If you need to make a hotfix for a production issue, it not only gives you somewhere to cleanly branch from, but also somewhere to merge back into afterwards.

Why is that useful? At heart, Gitflow (like the very similar SCM strategies of the 90s) is all about putting in just enough isolation so that different teams / functions can work at their own pace without blocking each other.

It's perfectly possible - and legit - for `develop` to be weeks ahead of `master`, and for `develop` to be incompatible with `master`. Not everyone can - or should - release early and release often. It's also not unusual for the teams maintaining production to be different from the teams working on the next release. That can make it very difficult to merge the fixes back down into `develop`. By having `master` to branch from and merge back to, the production support teams have an easier life in between releases.

Why is `master` a better choice for that than using tags? Collapsing releases and hotfixes back down into the `master` branch keeps things clean and manageable for anyone using any of the more visual tools for working with Git. If you've got lots of long-lived hotfix branches made directly from tags, I would imagine those tools are a bit harder to work with. The main way around that is to merge them into somewhere. Without `master`, there isn't always somewhere to merge them into.

`release/<version>` branches aren't there for long-term support, not in the Gitflow model. They're a staging area, for you to test the release code base as a whole without stopping new development work. In the past, we've talked about introducing `support/1.x` branches for long-term support. They can be emulated today using the `git hf init -a` approach - just replace `master` with `support/1.x` and `develop` with `support/1.x-develop` in the prompts. (I don't know if anyone's actually doing that or not).

Even if you and your organisation benefit from going down to just one long-lived branch - and I'm not clear at all that there are genuine benefits - as explained above, that's not a one-size-fits-all approach. The Gitflow model successfully scales all the way down to a single developer, and all the way up to large enterprise and Government IT projects. Maybe I need to make some better training material to help with that, I don't know. (Training's definitely on my TODO list, as I need a way for this project to fund my time on it in the future).

I hope that helps.

**Comment by EugenMayer** [comment]
Thank you for the elaborated answer and the insight!

> The master branch in Gitflow serves an important purpose: it's the only branch that contains only released code. If you need to make a hotfix for a production issue, it not only gives you somewhere to cleanly branch from, but also somewhere to merge back into afterwards.

Well, if you need to provide hotfixes for a release, IMHO should have done a `release/VERSION` anyway - and that is where those hotfixes are based on (anyway). It is anyway better to ask the question "hotfix for which release?"

> It's perfectly possible - and legit - for develop to be weeks ahead of master, and for develop to be incompatible with master. Not everyone can - or should - release early and release often. It's also not unusual for the teams maintaining production to be different from the teams working on the next release. That can make it very difficult to merge the fixes back down into develop. By having master to branch from and merge back to, the production support teams have an easier life in between releases.

While we really value that production support being easy, the `develop` branch has not helped specificly. A `master` branch with the semantic meaning of `develop`, so edge code + `release/<>` does the job perfectly fine and reduces the branch complexity.

> Why is master a better choice for that than using tags? Collapsing releases and hotfixes back down into the master branch keeps things clean and manageable for anyone using any of the more visual tools for working with Git. If you've got lots of long-lived hotfix branches made directly from tags, I would imagine those tools are a bit harder to work with. The main way around that is to merge them into somewhere. Without master, there isn't always somewhere to merge them into.

Hotfix branches are very short lived for us always - the merge target is the `release/<>` you want to hotfix + `master` ( of course )

> release/<version> branches aren't there for long-term support, not in the Gitflow model. They're a staging area, for you to test the release code base as a whole without stopping new development work. In the past, we've talked about introducing support/1.x branches for long-term support. They can be emulated today using the git hf init -a approach - just replace master with support/1.x and develop with support/1.x-develop in the prompts. (I don't know if anyone's actually doing that or not).

AFAICS `support/` popped up fairly late and i cannot really see a huge benefit in splitting `release/<>` and `support/<>` - we do `release/MAJOR.MINOR` ( never patch ). So all patches go on top of that branch. Every patch release is a tag ( as every other release also of course ). 
So you can access every single release and you can support your Minors as long as you need / plan too. Cannot see a need of support here  ( too much ).

> Even if you and your organisation benefit from going down to just one long-lived branch - and I'm not clear at all that there are genuine benefits - as explained above, that's not a one-size-fits-all approach. The Gitflow model successfully scales all the way down to a single developer, and all the way up to large enterprise and Government IT projects. Maybe I need to make some better training material to help with that, I don't know. (Training's definitely on my TODO list, as I need a way for this project to fund my time on it in the future).

I would disagree on the point that gitlfow scales all the way down - i think that is one of it's major flaws of in general (proven ofer time maybe). It is way to heavy duty and clunky for small size projects especially since it lacks most of the convenience features a small OSS project ( or commercial ) gets from not only doing PRs but actually using the PR workflow on the github/bitbucket/gitlab website, keeping all PRs in the history and being able to track them all down with all the otherwise lost information. E.g. if you squash-merge with gitflow, all the things of the old branch are lost. Using github, you can always go back and check the PR and all the single commits before the squash, if that ever is interesting. There is evern more to that though, the entire review chat, review comments which you later can dig into if issues occur and "they have been doubts it works anyway in the PR..lets dig down that hole"

The reason of "overbranching" is one if the main issues i see and that is why we also have those "master only" efforts ( which seem to me a different side of extreme though ).

As a product team, we really see a lot of value in gitflow in terms of supporting releases, hotfixes and several features at the same time ( including the integration branch which can be either `master` or `develop` ). So i do not really argue against Gitflow in that sense.

I still cannot see a real benefit for the `develop` branch, but be that up to the individual needs of the teams / workflows.

One of the biggest issues i see right now is that hubflow does only use PRs on github as a "option" and does merge on the cli, not using the github API, which leads to several issues with the meta-data which is preserved on github. Understanding that this whole thing is basically a huge bash "something" doing curl requests, oAuth and all sort of things we would need for the API support, is out of scope.

Seems like we are opting in to write and own go based github client ( using githubs official API libraries ) and golangs git support. 
Using https://github.com/cli/cli will be a good starting point where we basically only need to automate some of the custom BL and that's about it.

Maybe this what you suggested anyway, there is no size "fits them all", seems like most of us stick to the actual slim down process each one of us prefers most.

**Comment by EugenMayer** [comment]
If you like, close the issue anytime - thank you for sharing you POV and insight, was very helpful
